baseurl: "/gemma-zaken"
apiname: "GEMMA Zaken"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Productvisie
    subnav:
      - title: Productvisie
        path: /_content/productvisie
  - title: API-Standaarden
    subnav:
      - title: Zaken API
        path: /_content/standaard/zaken
      - title: Documenten API
        path: /_content/standaard/documenten

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

github: hdksi/gemma-zaken

theme: jekyll-theme-cayman

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

project_name: /gemma-zaken

standard_family: nvt
